### ISSUE TITLE
自动生成TAG采集的时候响应很慢

### ISSUE THREAD

**Issue by 2042408916** [maccmspro/maccms10#16]
自动生成TAG采集的时候响应很慢, 北京,杭州, 福建都尝试过. 前些天还正常,今天特别慢
看到 mac_get_tag  中请求 http://api.maccms.pro/keyword/index?name=xxxx 很慢
有人今天 碰到吗, 现在是关掉生成tag 速度很快

**Comment by caoboruicbr** [comment]
这是假的，别信magicblack才是真的
