### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by Inkqaqz** [maccmspro/maccms10#18]
进入后台，点击基础-->友链管理-->添加，在名称处link_name[]插入payload:test”><img/src=1 onerror=alert(1)>
![图片](https://user-images.githubusercontent.com/81867137/141281876-793a2dda-2fe2-422d-9046-eed96fb45133.png)
点击保存，成功触发XSS，此外，该处也存在CSRF漏洞，可以结合CSRF漏洞进行利用
![图片](https://user-images.githubusercontent.com/81867137/141281910-c86aaf8a-8feb-44a0-80cf-ce380272734f.png)

**Comment by maccmspro** [comment]
感谢，已统一修复
