### ISSUE TITLE
挂这么多，良心不痛吗

### ISSUE THREAD

**Issue by denghuiquan** [maccmspro/maccms10#5]
https://github.com/maccmspro/maccms10/blob/9612ffe7c649bd185b6beb7de58f3629bd5f2225/application/admin/view/system/configplay.html#L177
![image](https://user-images.githubusercontent.com/5303970/125417197-22a5251e-7271-4ccf-b272-c9ad77b56463.png)

**Comment by brui233** [comment]
都不知道那个是真的maccms，早用seacms了

**Comment by maccmspro** [comment]
这个是播放器调用,你也可以选择性去掉 自己本地化，代码都是开源的
