### ISSUE TITLE
官方加这段代码是为了什么？

### ISSUE THREAD

**Issue by dianyings** [maccmspro/maccms10#6]
https://github.com/maccmspro/maccms10/blob/1643ed853c655f12aa9b9cd271aa60c2e9646acb/static/js/player.js#L51

**Comment by brui233** [comment]
是不是player里面的？
那就是引用union.macvideojs.com的top10.js
我现在早用海洋了，苹果这边不知道那个是真的

**Comment by maccmspro** [comment]
这个是播放器调用,你也可以选择性去掉 自己弄一个js，代码都是开源的

**Comment by maccmspro** [comment]
这个issue先关闭了，欢迎重开提出建设性意见。
