### ISSUE TITLE
@todo

### ISSUE THREAD

**Issue by dianyings** [maccmspro/maccms10#7]
https://github.com/maccmspro/maccms10/blob/1643ed853c655f12aa9b9cd271aa60c2e9646acb/application/common/model/Actor.php#L293-L297

**Comment by dianyings** [comment]
$page_total = floor(abs($data_count - $lp['num']) / $lp['num']) + 1;

**Comment by maccmspro** [comment]
感谢反馈，将在后续版本里修复。
