### ISSUE TITLE
专题影片数bug

### ISSUE THREAD

**Issue by dianyings** [maccmspro/maccms10#8]
https://github.com/maccmspro/maccms10/blob/1643ed853c655f12aa9b9cd271aa60c2e9646acb/application/common/model/Topic.php#L38-L49

vod_list数据来源topic_rel_vod+vod_tag，显示专题影片数时只处理了topic_rel_vod的数量，vod_tag的数量遗漏了

**Comment by maccmspro** [comment]
专题影片数只需要关注topic_rel_vod的数量，和vod_tag无关。
